import type { Trip, Day, Item, Accommodation } from './types'

function formatTime(t?: string) {
  if (!t) return ''
  const [h, m] = t.split(':')
  return `${h}:${m}`
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString('en-AU', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  })
}

function formatDateShort(dateStr: string) {
  return new Date(dateStr).toLocaleDateString('en-AU', {
    day: 'numeric', month: 'short', year: 'numeric',
  })
}

function itemLine(item: Item): string {
  const parts: string[] = []

  // Time
  if (item.start_time) {
    const time = item.end_time
      ? `${formatTime(item.start_time)} – ${formatTime(item.end_time)}`
      : formatTime(item.start_time)
    parts.push(time)
  }

  // Title
  parts.push(item.title || 'Untitled')

  // Location
  if (item.location) parts.push(`@ ${item.location}`)
  if (item.location_from && item.location_to) {
    parts.push(`(${item.location_from} → ${item.location_to})`)
  }

  // Duration
  if (item.duration_minutes) {
    const h = Math.floor(item.duration_minutes / 60)
    const m = item.duration_minutes % 60
    const dur = h > 0 && m > 0 ? `${h}h ${m}m` : h > 0 ? `${h}h` : `${m}m`
    parts.push(`[${dur}]`)
  }

  // Confirmation
  if (item.confirmed) {
    parts.push(item.confirmation ? `✓ ${item.confirmation}` : '✓ Confirmed')
  }

  // Notes/subtitle
  if (item.subtitle) parts.push(`— ${item.subtitle}`)

  return `    • ${parts.join('  ')}`
}

function accomForDate(accom: Accommodation[], date: string): Accommodation | undefined {
  return accom.find((a) => a.check_in <= date && a.check_out > date)
}

export function buildTripExport(trip: Trip, days: Day[], accom: Accommodation[]): string {
  const lines: string[] = []

  // Header
  lines.push(`# ${trip.name}`)
  lines.push(`${formatDateShort(trip.start_date)} — ${trip.duration_days} days`)
  lines.push('')

  // Stats
  const allItems = days.flatMap((d) => d.items)
  const flights = allItems.filter((i) => i.type === 'flight').length
  const activities = allItems.filter((i) => !['flight', 'transport'].includes(i.type)).length
  const transport = allItems.filter((i) => i.type === 'transport').length
  lines.push(`Overview: ${trip.duration_days} days · ${flights} flights · ${transport} transport · ${activities} activities · ${accom.length} accommodation${accom.length !== 1 ? 's' : ''}`)
  lines.push('')
  lines.push('─'.repeat(60))
  lines.push('')

  // Days
  for (const day of days) {
    const sorted = [...day.items].sort((a, b) => {
      if (!a.start_time && !b.start_time) return a.sort_order - b.sort_order
      if (!a.start_time) return 1
      if (!b.start_time) return -1
      return a.start_time.localeCompare(b.start_time)
    })

    lines.push(`## Day ${day.day_index} — ${formatDate(day.date)}`)

    // Accommodation for this night
    const stay = accomForDate(accom, day.date)
    if (stay) {
      const stayLine = stay.address
        ? `${stay.name}, ${stay.address}`
        : stay.name
      lines.push(`  🏨 Staying at: ${stayLine}${stay.confirmed ? ' ✓' : ''}`)
    }

    // Day notes
    if (day.notes?.trim()) {
      lines.push(`  📝 Notes: ${day.notes.trim()}`)
    }

    lines.push('')

    if (sorted.length === 0) {
      lines.push('    (No items planned)')
    } else {
      for (const item of sorted) {
        lines.push(itemLine(item))
        if (item.notes?.trim()) {
          // Indent notes under the item
          item.notes.trim().split('\n').forEach((note) => {
            lines.push(`      ↳ ${note.trim()}`)
          })
        }
      }
    }

    lines.push('')
  }

  lines.push('─'.repeat(60))
  lines.push('')
  lines.push('Generated by Travel Planner. Paste into an AI tool for recommendations, optimisations or gap analysis.')

  return lines.join('\n')
}