import type { Itinerary, ItineraryLeg } from './types'
import { computeBudget } from './types'

function addDays(date: Date, days: number): Date {
  const d = new Date(date); d.setDate(d.getDate() + days); return d
}

function fmtDate(d: Date) {
  return d.toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' })
}

function fmtDateShort(d: Date) {
  return d.toLocaleDateString('en-AU', { day: 'numeric', month: 'short' })
}

function fmtAud(n: number) {
  return n === 0 ? '—' : `$${Math.round(n).toLocaleString('en-AU')}`
}

function computeStartDates(legs: ItineraryLeg[], start: string): Map<string, Date> {
  const map = new Map<string, Date>()
  let cursor = new Date(start + 'T00:00:00')
  for (const leg of legs) { map.set(leg.id, new Date(cursor)); cursor = addDays(cursor, leg.duration_days) }
  return map
}

function legLine(leg: ItineraryLeg, startDate: Date): string[] {
  const lines: string[] = []
  const endDate = addDays(startDate, leg.duration_days - 1)
  const dateRange = `${fmtDateShort(startDate)} – ${fmtDateShort(endDate)}`

  lines.push(`  • [${leg.mode}] ${leg.destination} (${leg.region}) — ${dateRange} · ${leg.duration_days}d`)

  if (leg.mode === 'Transit' && leg.transit) {
    const t = leg.transit
    const route = [t.from_airport, t.via_airport, t.to_airport].filter(Boolean).join(' → ')
    const parts = [route, t.airline, t.fare_type !== 'Full fare' ? t.fare_type : null, t.flight_class]
      .filter(Boolean)
      .join(' · ')
    if (parts) lines.push(`      ✈ ${parts}`)
    if (t.cost_aud) lines.push(`      Cost: ${fmtAud(Number(t.cost_aud))}`)
    if (t.booking_notes) lines.push(`      Notes: ${t.booking_notes}`)
  }

  if (leg.activities.length > 0) {
    lines.push('      Activities:')
    for (const a of leg.activities) {
      const cost = a.cost_aud ? ` (${fmtAud(Number(a.cost_aud))})` : ''
      const tier = a.tier !== 'nice' ? ` [${a.tier}]` : ''
      lines.push(`        - ${a.description}${tier}${cost}`)
    }
  }

  if (leg.accom.length > 0) {
    lines.push('      Accommodation:')
    for (const a of leg.accom) {
      const name = a.name || a.accom_type
      const cost = a.cost_per_night_aud ? ` — ${fmtAud(Number(a.cost_per_night_aud))}/night` : ''
      lines.push(`        - ${name} (${a.accom_type}, ${a.booking_status})${cost}`)
      if (a.notes) lines.push(`          ↳ ${a.notes}`)
    }
  }

  if (leg.notes?.trim()) lines.push(`      📝 ${leg.notes.trim()}`)

  return lines
}

export function buildItineraryExport(itinerary: Itinerary, legs: ItineraryLeg[]): string {
  const lines: string[] = []
  const startDates = computeStartDates(legs, itinerary.start_date)

  lines.push(`# ${itinerary.title}${itinerary.year_label ? ` — ${itinerary.year_label}` : ''}`)
  lines.push(`Starts ${fmtDate(new Date(itinerary.start_date + 'T00:00:00'))}`)
  lines.push('')

  const budget = computeBudget(legs)
  const regions = new Set(legs.map((l) => l.region)).size
  const dests = legs.filter((l) => l.mode !== 'Transit').length
  const totalDays = legs.reduce((s, l) => s + l.duration_days, 0)
  lines.push(`Overview: ${regions} regions · ${dests} destinations · ${totalDays} days`)
  lines.push(`Budget: Transit ${fmtAud(budget.transitTotal)} · Accom ${fmtAud(budget.accomTotal)} · Activities ${fmtAud(budget.activitiesTotal)} · Living ${fmtAud(budget.livingTotal)} · Total ${fmtAud(budget.grandTotal)}`)
  lines.push('')
  lines.push('─'.repeat(60))
  lines.push('')

  // Group consecutive legs by region, same as the on-screen view
  let currentRegion: string | null = null
  for (const leg of legs) {
    if (leg.region !== currentRegion) {
      currentRegion = leg.region
      lines.push(`## ${currentRegion}`)
    }
    const start = startDates.get(leg.id)!
    lines.push(...legLine(leg, start))
    lines.push('')
  }

  if (itinerary.notes?.trim()) {
    lines.push('─'.repeat(60))
    lines.push('')
    lines.push(`Notes: ${itinerary.notes.trim()}`)
    lines.push('')
  }

  lines.push('─'.repeat(60))
  lines.push('')
  lines.push('Generated by Travel Planner. Paste into an AI tool for recommendations, optimisations or gap analysis.')

  return lines.join('\n')
}